name: rna-splicing
channels:
  - conda-forge
  - bioconda
dependencies:
  - nextflow=21.10.0
  - salmon=1.6.0
  - trim-galore=0.6.7
  - suppa=2.3
  - numpy=1.21.4
  - pandas=1.3.4
  - openjdk=10.0.2
  - python=3.7.12
  - perl=5.32.1
  - scipy=1.7.3
  - pip=21.3.1
